### ISSUE TITLE
Want to use vim keymap in easy mde. 

### ISSUE THREAD

**Issue by polodev** [Ionaru/easy-markdown-editor#593]
**Require to add vim KeyMap**

```js
easymde.codemirror.setOption('keyMap', 'vim'); 
```

getting following error 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Zo (easymde.min.js:7:128459)
    at easymde.min.js:7:138057
    at da (easymde.min.js:7:138084)
    at ca (easymde.min.js:7:137852)
    at easymde.min.js:7:140370
    at Ma.ba (easymde.min.js:7:140594)
    at HTMLDivElement.<anonymous> (easymde.min.js:7:80947)Understand this error
easymde.min.js:7 
```

Is there any way I can Use Easy Markdown Editor with vim keybindings

**Comment by BrandonDyer64** [comment]
Did you include the `keymap/vim.js` file as mentioned in the [CodeMirror docs](https://codemirror.net/5/demo/vim.html)?
